serverPort: 8080
hook: /dingtalk/alerts
security:
  token: 
    header: Authorization
    value: 123456
templates:
- name: mysqlaudit
  content: |
    {"type": "markdown", "msg": {"title", "{{.title}}", "content": "{{.message}}"}}
- name: mysqlaudit-idempotent
  content: |
    {{ (index .alerts 0).labels.query }}-{{ (index .alerts 0).labels.date }}-{{ (index .alerts 0).labels.user }}
targets:
- name: mysqlaudit
  enabled: true
  url: https://api.dingtalk.com/robot?ak=23249304329435945
  bodyTemplate: mysqlaudit
  idempotentTemplate: mysqlaudit-idempotent
  conditions:
  - key: $.alerts[0].labels.alert_type
    operator: Eq
    value: mysqlaudit

